services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: app
      RABBITMQ_DEFAULT_PASS: app
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build: ./server
    environment:
      APP_DB_DSN: postgresql+psycopg://app:app@postgres:5432/app
      APP_RMQ_URL: amqp://app:app@rabbitmq:5672/
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq

  consumer:
    build: ./consumer
    environment:
      APP_DB_DSN: postgresql+psycopg://app:app@postgres:5432/app
      APP_RMQ_URL: amqp://app:app@rabbitmq:5672/
    depends_on:
      - postgres
      - rabbitmq

  prometheus:
    image: prom/prometheus:v2.54.1
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - api

  grafana:
    image: grafana/grafana:11.1.4
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

volumes:
  pgdata: {}
